### ISSUE TITLE
test out sounds on an online vocoder to see which sounds are fun to mix voices with

### ISSUE THREAD

**Issue by Austinchambers1** [Austinchambers1/FuseMe#4]

**Comment by brotatotes** [comment]
includes finding a bunch of fun/crazy/random sounds that might create hilarious results
 - celebrities
 - memes
 - animal sounds
 - autistic noises (dylan)
 - electronic sound effects

**Comment by Austinchambers1** [comment]
Prem said mixing specifically with music like in the example was the coolest in his opinion
