### ISSUE TITLE
Style Flask Site

### ISSUE THREAD

**Issue by Austinchambers1** [Austinchambers1/FuseMe#8]
I am really,really,really bad at this so help would be appreciated, we can save this for the end tho once everything else is working

**Comment by brotatotes** [comment]
Simplicity suffices. [This](https://headline-gen.herokuapp.com/) is what Adam made at the hackathon with Flask hosted on Heroku.

**Comment by brotatotes** [comment]
You could probably even rip off his [CSS page](https://github.com/AdamHe17/headlinegenerator)

**Comment by Austinchambers1** [comment]
that is exactly whats gonna happen tbh. Thanks!

**Comment by Austinchambers1** [comment]
Note: right now when you click upload it looks like nothing is happening, but trust me it is is working. You guys should add some jquery to make it print a message like "uploaded!" and make the form disappear

**Comment by Austinchambers1** [comment]
looks fucking good
