### ISSUE TITLE
survey lol

### ISSUE THREAD

**Issue by brotatotes** [Austinchambers1/FuseMe#9]
currently using Google Forms with links to audio on google drive (don't have any audio yet though)

**Comment by Austinchambers1** [comment]
also send the survey to people 8===D

**Comment by brotatotes** [comment]
Things the survey needs
 - 2 more different vocal speech recordings. @Austinchambers1, make sure they are not of famous quotes in which the surveyor might easily recognize. 
 - I'm thinking questions about 3 different types of fusions:
     - one with a texture (probably fire since that's cool, could also be rain, static)
     - one with synthy sound (probably will use the *defeat me in battle* one we already have)
     - one with a really crazy sound like the tiger/rooster. (even if we think it sounds bad, that's exactly why it should be included in the survey)

Each of the above fusions should be of different speech, (aka say different things)

**Comment by brotatotes** [comment]
In summary:

@Austinchambers1: 2 recordings please, since I think the anarchy one might be a little recognizable. What you say is up to you.

@brotatotes: I'll find some sounds to fuse, aka fire, rain, maybe another animal, idk

@JunhaoSLi: Once all the sounds are ready, we'll let you know. Please fuse them.

**Comment by brotatotes** [comment]
live!
